@extends('layouts.app')
@section('title', 'Thanh toán & Hẹn giờ lấy món · FoodGo')
@section('content')
<div class="checkout-heading"><a class="checkout-back" href="{{ route('home') }}"><span class="material-symbols-outlined">arrow_back</span></a><div><div><span class="step-label">Bước 2/2</span><strong>Xác nhận & Lên lịch hẹn lấy món</strong></div><small>Tránh xếp hàng đông đúc giờ cao điểm tại căn tin FoodGo</small></div><div class="checkout-trust"><span><span class="material-symbols-outlined">verified_user</span>Ưu tiên theo giờ hẹn</span><span><span class="material-symbols-outlined">bolt</span>Nhận món nhanh chóng</span></div></div>
@if(session('status'))<div class="alert">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert error-alert">{{ $errors->first() }}</div>@endif
@if($cart->items->isNotEmpty())
<div class="checkout-layout"><form id="checkout-form" class="checkout-options" method="POST" action="{{ route('web.orders.store') }}">@csrf
    <section class="checkout-section"><div class="checkout-section-title"><h2><span class="material-symbols-outlined">restaurant</span>1. Hình thức dùng bữa</h2><span class="eco-label">Thân thiện môi trường</span></div><div class="choice-grid"><label class="choice-card active"><input checked type="radio" name="fulfillment_type" value="dine_in"><span class="material-symbols-outlined">table_restaurant</span><strong>Ăn tại căn tin</strong><small>Dùng khay và đĩa sứ giữ nhiệt, nước mát miễn phí tại chỗ.</small><em>Tiết kiệm phí đóng gói</em></label><label class="choice-card"><input type="radio" name="fulfillment_type" value="takeaway"><span class="material-symbols-outlined">takeout_dining</span><strong>Đóng gói mang đi</strong><small>Hộp giấy sinh học và túi quai xách tiện lợi.</small><em>+2.000đ mỗi phần</em></label></div></section>
    <section class="checkout-section"><div class="checkout-section-title"><h2><span class="material-symbols-outlined">schedule</span>2. Khung giờ nhận món chính xác</h2><span class="live-label"><i></i>Cập nhật lưu lượng trực tiếp</span></div><div class="rush-notice"><span class="material-symbols-outlined">crisis_alert</span><div><strong>Khung giờ trưa thường đông khách</strong><small>Chọn thời gian phù hợp để bếp chuẩn bị và giao món đúng hẹn.</small></div></div><div class="pickup-field"><label for="pickup_slot">Ngày và giờ nhận món</label><input id="pickup_slot" type="datetime-local" name="pickup_slot" value="{{ old('pickup_slot', now()->addHour()->startOf('minute')->format('Y-m-d\TH:i')) }}" min="{{ now()->addMinutes(15)->format('Y-m-d\TH:i') }}" required><small>Các khung giờ cách nhau 15 phút được khuyến nghị.</small></div><div class="traffic-bars" aria-label="Mật độ dự kiến theo khung giờ"><span style="height:28%"></span><span style="height:48%"></span><span class="recommended" style="height:68%"></span><span class="busy" style="height:95%"></span><span style="height:58%"></span><span style="height:35%"></span></div></section>
    <section class="checkout-section"><div class="checkout-section-title"><h2><span class="material-symbols-outlined">storefront</span>3. Vị trí quầy nhận món</h2><span class="step-label">Tự động gom 1 mã</span></div><p class="muted">Món của bạn được chuẩn bị tại các quầy chuyên biệt và gom về một điểm nhận.</p><div class="counter-grid"><div class="counter-card"><b>01</b><div><strong>Quầy Cơm phần & Món nóng</strong><small>Phụ trách món nóng và cơm</small></div></div><div class="counter-card"><b>04</b><div><strong>Quầy Trà & Nước pha chế</strong><small>Phụ trách đồ uống và món phụ</small></div></div></div></section>
    <section class="checkout-section"><div class="checkout-section-title"><h2><span class="material-symbols-outlined">account_balance_wallet</span>4. Phương thức thanh toán</h2><span class="muted">Mã hóa an toàn</span></div><label class="payment-card active"><input checked type="radio" name="payment_method" value="foodgo_wallet"><span class="payment-icon material-symbols-outlined">badge</span><span><strong>Ví FoodGo / Thẻ Sinh Viên - Nhân Viên</strong><small>Số dư hiện tại: {{ number_format(auth()->user()->wallet_balance, 0, ',', '.') }} đ</small></span><span class="material-symbols-outlined">check_circle</span></label><div class="payment-card disabled"><span class="payment-icon material-symbols-outlined">qr_code_2</span><span><strong>Quét mã QR Ngân hàng</strong><small>Sẽ được hỗ trợ trong phiên bản tiếp theo.</small></span></div></section>
    <label class="payment-card"><input type="radio" name="payment_method" value="cash_on_delivery"><span class="payment-icon material-symbols-outlined">payments</span><span><strong>Thanh to&aacute;n khi nh&#7853;n m&oacute;n</strong><small>Thanh to&aacute;n b&#7857;ng ti&#7873;n m&#7863;t t&#7841;i qu&#7847;y khi nh&#7853;n &#273;&#7911; m&oacute;n.</small></span><span class="material-symbols-outlined">check_circle</span></label>
</form>
<aside class="checkout-summary"><div class="checkout-section-title"><div><h2>Chi tiết đơn hàng</h2><small class="muted">{{ $cart->items->sum('quantity') }} món</small></div><span class="eco-label">{{ $cart->items->sum('quantity') }} món</span></div><div class="checkout-items">@foreach($cart->items as $item)<div class="checkout-item">@if($item->food->displayImageUrl())<img src="{{ $item->food->displayImageUrl() }}" alt="{{ $item->food->name }}">@else<span class="cart-food-placeholder">{{ $item->food->displayEmoji() }}</span>@endif<div><strong>{{ $item->food->name }}</strong><small>{{ implode(' · ', $item->optionLabels()) }}</small><small>{{ number_format($item->effective_unit_price, 0, ',', '.') }} đ / phần</small><form method="POST" action="{{ route('cart.items.update', $item) }}">@csrf @method('PATCH')<input type="hidden" name="quantity" value="{{ $item->quantity }}"><button class="mini-action" type="submit">Số lượng: {{ $item->quantity }}</button></form></div><strong>{{ number_format($item->quantity * $item->effective_unit_price, 0, ',', '.') }} đ</strong><form method="POST" action="{{ route('cart.items.destroy', $item) }}">@csrf @method('DELETE')<button class="remove-item" type="submit" aria-label="Xóa {{ $item->food->name }}"><span class="material-symbols-outlined">close</span></button></form></div>@endforeach</div><a class="continue-shopping" href="{{ route('home') }}"><span class="material-symbols-outlined">arrow_back</span>Tiếp tục chọn món</a><div class="summary-location"><span class="material-symbols-outlined">location_on</span><div><strong>Căn tin FoodGo</strong><small>Nhận món tại quầy gom nhanh</small></div></div><div class="summary-lines"><div><span>Tạm tính</span><span>{{ number_format($total, 0, ',', '.') }} đ</span></div><div><span>Phí đóng gói mang đi</span><span>2.000 đ / phần</span></div><div><span>Thanh toán</span><span class="green-text">Ví FoodGo</span></div></div><div class="summary-total"><span>Tổng thanh toán</span><strong>{{ number_format($total, 0, ',', '.') }} đ</strong></div><button class="button full checkout-submit" type="submit" form="checkout-form"><span class="material-symbols-outlined">restaurant</span>Xác nhận đặt món & nhận mã lấy đồ</button><div class="safe-note"><span class="material-symbols-outlined">verified_user</span>Đơn chưa thanh toán sẽ tự hủy sau 15 phút và hoàn tồn kho</div></aside></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const radios=document.querySelectorAll('[name="fulfillment_type"]');const feeLine=document.querySelector('.summary-lines div:nth-child(2)');const totalEl=document.querySelector('.summary-total strong');const base={{ (float) $total }};const portions={{ $cart->items->sum('quantity') }};const update=()=>{const takeaway=document.querySelector('[name="fulfillment_type"]:checked')?.value==='takeaway';feeLine.style.display=takeaway?'flex':'none';totalEl.textContent=new Intl.NumberFormat('vi-VN').format(base+(takeaway?portions*2000:0))+' đ'};radios.forEach(radio=>radio.addEventListener('change',update));update()});</script>
@else
<section class="checkout-section cart-empty-page"><span class="material-symbols-outlined">shopping_bag</span><h1>Giỏ hàng đang trống</h1><p class="muted">Hãy chọn món trước khi lên lịch nhận.</p><div class="actions"><a class="button" href="{{ route('home') }}">Chọn món ngay</a><button class="button secondary" type="button" disabled>Đặt hàng</button></div></section>
@endif
@endsection
