@extends('layouts.app')
@section('title', ($user->exists ? 'Chỉnh sửa' : 'Tạo').' tài khoản · FoodGo')
@section('content')
@include('admin.partials.nav')
<div class="management-head"><div><div class="eyebrow">Phân quyền hệ thống</div><h1>{{ $user->exists ? 'Chỉnh sửa tài khoản' : 'Tạo tài khoản' }}</h1></div><a class="button secondary" href="{{ route('admin.users.index') }}">Quay lại</a></div>
@if(session('status'))<div class="alert">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert error-alert">{{ $errors->first() }}</div>@endif
<form class="form-panel" method="POST" action="{{ $user->exists ? route('admin.users.update', $user) : route('admin.users.store') }}">@csrf @if($user->exists)@method('PUT')@endif
<div class="form-grid"><div class="field"><label for="name">Họ và tên</label><input id="name" name="name" value="{{ old('name', $user->name) }}" required></div><div class="field"><label for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email', $user->email) }}" required></div><div class="field"><label for="student_id">Mã sinh viên</label><input id="student_id" name="student_id" value="{{ old('student_id', $user->student_id) }}"></div><div class="field"><label for="phone">Điện thoại</label><input id="phone" name="phone" value="{{ old('phone', $user->phone) }}"></div><div class="field"><label for="role">Vai trò</label><select id="role" name="role"><option value="customer" @selected(old('role', $user->role) === 'customer')>Khách hàng</option><option value="staff" @selected(old('role', $user->role) === 'staff')>Nhân viên</option><option value="admin" @selected(old('role', $user->role) === 'admin')>Quản trị</option></select></div><div class="field"><label for="wallet_balance">Số dư Ví FoodGo</label><input id="wallet_balance" type="number" name="wallet_balance" value="{{ old('wallet_balance', $user->wallet_balance ?? 0) }}" min="0" step="1000" required></div><div class="field"><label for="is_active">Trạng thái</label><select id="is_active" name="is_active"><option value="1" @selected(old('is_active', $user->is_active ?? true))>Hoạt động</option><option value="0" @selected(! old('is_active', $user->is_active ?? true))>Khóa tài khoản</option></select></div><div class="field"><label for="password">{{ $user->exists ? 'Mật khẩu mới' : 'Mật khẩu' }}</label><input id="password" type="password" name="password" minlength="8" @required(! $user->exists)></div><div class="field"><label for="password_confirmation">Nhập lại mật khẩu</label><input id="password_confirmation" type="password" name="password_confirmation" minlength="8" @required(! $user->exists)></div></div><div class="form-actions"><button class="button" type="submit">{{ $user->exists ? 'Lưu tài khoản' : 'Tạo tài khoản' }}</button></div>
</form>
@endsection
